openapi: 3.1.0
info:
  title: GourmetGate
  description: API specification for the GourmetGate project
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: development environment
  - url: 'https://gouga.com'
    description: production environment
paths:
  /categories:
    get:
      summary: Returns a list of all categories
      tags:
        - Categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        404:
          description: Not found
    post:
      summary: Create a new category
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: OK - note that category_id property will get replaced when creating new category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
  /categories/{categoryId}:
    get:
      summary: Get category by ID
      tags:
        - Categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Not found
    put:
      summary: Update category by ID
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    delete:
      summary: Delete a category by ID
      tags:
        - Categories
      parameters:
        - in: path
          name: replacementId
          schema:
            type: string
            format: UUID
          required: true
          description: Id of category that replaces the old one.
      responses:
        200:
          description: OK
  /items:
    get:
      summary: Returns a list of all items
      tags:
        - Items
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        404:
          description: Not found
    post:
      summary: Create a new item
      tags:
        - Items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        200:
          description: OK - note that itemId property will get replaced when creating new category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
  /item/{itemId}:
    get:
      summary: Get item by ID
      tags:
        - Items
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        404:
          description: Not found
    put:
      summary: Update item by ID
      tags:
        - Items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
    delete:
      summary: Delete an item by ID
      tags:
        - Items
      responses:
        200:
          description: OK
  /variant:
    get:
      summary: Returns a list of all variants
      tags:
        - Variant
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VariantResponse"
        404:
          description: Not found
    post:
      summary: Create a new variant
      tags:
        - Variant
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Variant"
      responses:
        200:
          description: OK - note that variant_id property will get replaced when creating new variant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variant"
  /variant/{variantId}:
    get:
      summary: Get variant by ID
      tags:
        - Variant
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variant"
        404:
          description: Not found
    put:
      summary: Update variant by ID
      tags:
        - Variant
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Variant"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variant"
    delete:
      summary: Delete a variant by ID
      tags:
        - Variant
      responses:
        200:
          description: OK
  /vat:
    get:
      summary: Returns a list of all vat percentages
      tags:
        - Vat
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VatResponse"
        404:
          description: Not found
    post:
      summary: Create a new vat
      tags:
        - Vat
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vat"
      responses:
        200:
          description: OK - note that vat_id property will get replaced when creating new category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vat"
  /vat/{vatId}:
    get:
      summary: Get vat by ID
      tags:
        - Vat
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vat"
        404:
          description: Not found
    put:
      summary: Update vat by ID
      tags:
        - Vat
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vat"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vat"
    delete:
      summary: Delete a vat by ID
      tags:
        - Vat
      responses:
        200:
          description: OK
  /query:
    post:
      summary: Returns a list of requested entities
      tags:
        - Query
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryRestriction"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryResponse"

components:
  schemas:
    Category:
      type: object
      properties:
        categoryId:
          type: string
          description: 'Unique identifier of the category'
          format: UUID
          example: 'fb6259f1-106c-40f5-898b-d3c64216a732'
        name:
          type: string
          description: 'Name of the category'
          example: 'Food'
    CategoryResponse:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
    Item:
      type: object
      properties:
        itemId:
          type: string
          description: 'Unique identifier of the item'
          format: UUID
          example: '826d9fc5-a0f1-4eec-8350-cc38a95f10f9'
        categoryId:
          type: string
          description: 'Id of the category the item belongs to'
          format: UUID
          example: 'fb6259f1-106c-40f5-898b-d3c64216a732'
        vatId:
          type: string
          description: 'Id of the vat percentage the item belongs to'
          format: UUID
          example: 'b9684004-ea58-4efc-b6a3-742a6ff9b256'
        name:
          type: string
          description: 'Name of the item'
          example: 'Fries'
        price:
          type: string
          format: CHF
          description: 'Selling price of the item in CHF inclusive vat'
          example: '5.00'
        cost:
          type: string
          format: CHF
          description: 'Purchase cost of the item (optional)'
          example: '1.85'
        available:
          type: boolean
          description: 'Indicates, if the item is available for purchase'
          example: 'true'
        variantIds:
          type: array
          description: 'Ids of variants that are activated for this item'
          items:
            type: string
            format: UUID
    ItemResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
    Variant:
      type: object
      properties:
        variantId:
          type: string
          format: UUID
          description: 'Unique identifier of the variant'
          example: 'c7ac57a0-79a1-42c7-8bb2-051637f54861'
        name:
          type: string
          format: UUID
          description: 'Name of the variant'
          example: 'Sauce'
        singleOption:
          type: boolean
          description: 'Indicates if only a single option of this variant allowed'
          example: 'false'
        options:
          type: array
          items:
            $ref: "#/components/schemas/VariantOption"
        itemIds:
          type: array
          items:
            type: string
            format: UUID
    VariantOption:
      type: object
      properties:
        variantOptionId:
          type: string
          format: UUID
          description: 'Unique identifier of the variant option'
          example: '57b56690-1099-4d57-ad34-dcdc69a0ee68'
        variantId:
          type: string
          format: UUID
          description: 'The variant the option belongs to'
          example: '70cc38a5-ddd8-4727-b2ee-4ddce9f30819'
        name:
          type: string
          description: 'The name of the variant option'
          example: 'Ketchup'
        additionalPrice:
          type: string
          format: CHF
          description: 'The price this option costs'
          example: '0.00'
    VariantResponse:
      type: object
      properties:
        variants:
          type: array
          items:
            $ref: "#/components/schemas/Variant"
    Vat:
      type: object
      properties:
        vatId:
          type: string
          format: UUID
          description: 'The unique identifier of the vat'
          example: '00e7abc6-6bc6-4749-9ad2-6a2ad243a252'
        percentage:
          type: string
          description: 'The vat percentage'
          example: '8.1'
        description:
          type: string
          description: 'The description of the vat'
          example: 'Swiss default vat percentage'
    VatResponse:
      type: object
      properties:
        vat:
          type: array
          items:
            $ref: "#/components/schemas/Vat"
    QueryRestriction:
      type: object
      properties:
        categoryRestriction:
          type: object
          description: 'Restrictions for finding categories'
          properties:
            categoryId:
              type: string
              format: UUID
              example: '6560e202-4fa6-417f-83bc-cba52feabe6f'
              description: 'Id of the category that should be fetched (get by key)'
            name:
              type: string
              example: 'Foo'
              description: 'Only categories containing the given value in the name are fetched (case in-sensitive)'
        itemRestriction:
          type: object
          properties:
            itemId:
              type: string
              format: UUID
              example: 'db761cd0-8346-4d96-8d50-e637878e598c'
              description: 'Id of the item that should be fetched (get by key)'
            name:
              type: string
              example: 'Coc'
              description: 'Only items containing the given value in the name are fetched (case in-sensitive)'
            categoryIds:
              type: array
              description: 'Categories the items have to belong to.'
              items:
                type: string
                format: UUID
                example: 'b34db246-06ba-4d5b-9f96-21113ca17073'
            available:
              type: boolean
              description: 'Indicates if the items have to be available or not.'
              example: 'true'
        variantRestriction:
          type: object
          properties:
            variantId:
              type: string
              format: UUID
              example: '9b092031-5781-4ec6-9aec-9e9487a99476'
              description: 'Id of the variant that should be fetched (get by key)'
            name:
              type: string
              example: 'Sau'
              description: 'Only variants containing the given value in the name are fetched (case in-sensitive)'
        vatRestriction:
          type: object
          description: 'Restrictions for finding vat percentages'
          properties:
            vatId:
              type: string
              format: UUID
              example: '137c1eb1-b644-4f5a-8d39-01d973f1b509'
              description: 'Id of the vat that should be fetched (get by key)'
    QueryResponse:
      type: object
      properties:
        categories:
          type: array
          description: 'A list of found categories.'
          items:
            $ref: "#/components/schemas/Category"
        items:
          type: array
          description: 'A list of found items.'
          items:
            $ref: "#/components/schemas/Item"
        variants:
          type: array
          description: 'A list of found variants.'
          items:
            $ref: "#/components/schemas/Variant"
        vat:
          type: array
          description: 'A list of found vat.'
          items:
            $ref: "#/components/schemas/Vat"

tags:
  - name: Categories
    description: A category of items to split them into groups
  - name: Items
    description: An item that can be purchased by the customer.
  - name: Variant
    description: A variant for an item.
  - name: Vat
    description: Vat percentages of purchasable items.
  - name: Query
    description: Endpoint used to query a set of entities based on a restriction.
