openapi: 3.1.0
info:
  title: GourmetGate
  description: API specification for the GourmetGate project
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: development environment
  - url: 'https://gouga.com'
    description: production environment
paths:
  /categories:
    get:
      summary: Returns a list of all categories
      tags:
        - Categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        404:
          description: Not found
    post:
      summary: Create a new category
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: OK - note that category_id property will get replaced when creating new category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
  /categories/{categoryId}:
    get:
      summary: Get category by ID
      tags:
        - Categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Not found
    put:
      summary: Update category by ID
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    delete:
      summary: Delete a category by ID
      tags:
        - Categories
      responses:
        200:
          description: OK
  /items:
    get:
      summary: Returns a list of all items
      tags:
        - Items
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        404:
          description: Not found
    post:
      summary: Create a new item
      tags:
        - Items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        200:
          description: OK - note that itemId property will get replaced when creating new category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
  /item/{itemId}:
    get:
      summary: Get item by ID
      tags:
        - Items
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        404:
          description: Not found
    put:
      summary: Update item by ID
      tags:
        - Items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
    delete:
      summary: Delete an item by ID
      tags:
        - Items
      responses:
        200:
          description: OK

components:
  schemas:
    Category:
      type: object
      properties:
        categoryId:
          type: string
          description: 'Unique identifier of the category'
          format: UUID
          example: 'fb6259f1-106c-40f5-898b-d3c64216a732'
        name:
          type: string
          description: 'Name of the category'
          example: 'Food'
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
    CategoryResponse:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
    Item:
      type: object
      properties:
        itemId:
          type: string
          description: 'Unique identifier of the item'
          format: UUID
          example: '826d9fc5-a0f1-4eec-8350-cc38a95f10f9'
        categoryId:
          type: string
          description: 'Id of the category the item belongs to'
          format: UUID
          example: 'fb6259f1-106c-40f5-898b-d3c64216a732'
        vatId:
          type: string
          description: 'Id of the vat percentage the item belongs to'
          format: UUID
          example: 'b9684004-ea58-4efc-b6a3-742a6ff9b256'
        name:
          type: string
          description: 'Name of the item'
          example: 'Fries'
        price:
          type: string
          format: CHF
          description: 'Selling price of the item in CHF inclusive vat'
          example: '5.00'
        cost:
          type: string
          format: CHF
          description: 'Purchase cost of the item (optional)'
          example: '1.85'
        available:
          type: boolean
          description: 'Indicates, if the item is available for purchase'
          example: 'true'
        variants:
          type: array
          items:
            $ref: "#/components/schemas/Variant"
    ItemResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
    Variant:
      type: object
      properties:
        variantId:
          type: string
          format: UUID
          description: 'Unique identifier of the variant'
          example: 'c7ac57a0-79a1-42c7-8bb2-051637f54861'
        name:
          type: string
          format: UUID
          description: 'Name of the variant'
          example: 'Sauce'
        singleOption:
          type: boolean
          description: 'Indicates if only a single option of this variant allowed'
          example: 'false'
        options:
          type: array
          items:
            $ref: "#/components/schemas/VariantOption"
    VariantOption:
      type: object
      properties:
        variantOptionId:
          type: string
          format: UUID
          description: 'Unique identifier of the variant option'
          example: '57b56690-1099-4d57-ad34-dcdc69a0ee68'
        variantId:
          type: string
          format: UUID
          description: 'The variant the option belongs to'
          example: '70cc38a5-ddd8-4727-b2ee-4ddce9f30819'
        name:
          type: string
          description: 'The name of the variant option'
          example: 'Ketchup'
        additionalPrice:
          type: string
          format: CHF
          description: 'The price this option costs'
          example: '0.00'



tags:
  - name: Categories
    description: A category of items to split them into groups
  - name: Items
    description: An item that can be purchased by the customer.
